### PR TITLE
Subsummary Sort & Replace

### PR DESCRIPTION
**Pull request by joshormond**
Added a subsummary for the fmTimestamp, adjusted sorts, and added an option to replace existing 'registered sessions'.

### CODE REVIEW

**Comment by jwillinghalpern** [comment]
Hey, the time summaries look great.

Can you clarify how to find/use the "replace" feature you added? I thought it was going to be called from the "My Session Paste Card", but that seems to not be changed.

**Comment by jwillinghalpern** [comment]
@joshormond Hey, the time summaries look great.

Can you clarify how to find/use the "replace" feature you added? I thought it was going to be called from the "My Session Paste Card", but that seems to not be changed.

**Comment by joshormond** [comment]
Check it now. I forgot to move over the change in the "Mark Found as Registered" change.

**Comment by jwillinghalpern** [comment]
Works great! I like the trick you used with show omitted, took me a sec. Thanks for the improvements

**Comment by joshormond** [comment]
It's like a Double Indiana Jones swap...

**Pull request merged**
